CREATE TABLE CW2.Users(
    userID INT identity(1,1) NOT NULL,  
    hashed_password VARCHAR(128) NOT NULL,
    locationID INT,
    roleID TINYINT NOT NULL,
    username VARCHAR(40) UNIQUE NOT NULL,
    email VARCHAR(60) CHECK (email LIKE '%@%'),
    phone_no INT,
    first_name VARCHAR(40),
    last_name VARCHAR(40),
    dob DATE,
    height DECIMAL(5,2),
    weight DECIMAL(5,2),
    marketing_language VARCHAR(50),
    about_me VARCHAR(700),
    preferred_unit_metric VARCHAR(10),
    time_preference_speed VARCHAR(10),
    CONSTRAINT pk_userID PRIMARY KEY (userID),
    CONSTRAINT fk_roleID FOREIGN KEY (roleID) REFERENCES CW2.Roles,
    CONSTRAINT fk_locationID FOREIGN KEY (locationID) REFERENCES CW2.Location(locationID),
    
);